Fintech.WebMVC/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CodeID.Helper;
using Fintech.Common;
using Fintech.Entity;
using Fintech.Facade;
using Fintech.WebMVC.Filter;
using Fintech.WebMVC.Models;
using Newtonsoft.Json;

namespace Fintech.WebMVC.Controllers
{
    //[@Authorize]
    public class BankController : Controller
    {
        // GET: Account
        public ActionResult Index()
        { 
            return View();
        }

        public ActionResult IntroAngularJs()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Insert(Banks bank)
        { 
            if (ModelState.IsValid)
            {
                try
                {
                    using (var facade = new BankFacade())
                    {
                        var status = await facade.Insert(bank);
                        if (status)
                        {
                            return Json(ApiResponse.OK(status));
                        }
                        else
                        {
                            return Json(ApiResponse.NotAcceptable(bank));
                        }

                    }
                }
                catch (Exception ex)
                {
                    return Json(ApiResponse.InternalServerError(ex.Message));
                }
            }
            else
            {
                return Json(ApiResponse.BadRequest(bank));
            }
        }

        [HttpPost]
        public async Task<ActionResult> Update(Banks bank)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var facade = new BankFacade())
                    {
                        var status = await facade.Update(bank);
                        if (status)
                        {
                            return Json(ApiResponse.OK(status));
                        }
                        else
                        {
                            return Json(ApiResponse.NotAcceptable(bank));
                        }

                    }
                }
                catch (Exception ex)
                {
                    return Json(ApiResponse.InternalServerError(ex.Message));
                }
            }
            else
            {
                return Json(ApiResponse.BadRequest(bank));
            }
        }

        [HttpPost]
        public async Task<ActionResult> Paging(PageRequest page)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var facade = new BankFacade())
                    {
                        var pgResult = await facade.GetPage(page);
                        var result = JsonConvert.SerializeObject(ApiResponse.OK(pgResult));
                        return Content(result, "application/json");
                    }
                }
                catch (Exception ex)
                {
                    return Json(ApiResponse.InternalServerError(ex.Message));
                }
            }
            else
            {
                return Json(ApiResponse.BadRequest(page));
            }
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var facade = new BankFacade())
                    {
                        var status = await facade.Delete(id);
                        if (status)
                        {
                            return Json(ApiResponse.OK(status));
                        }
                        else
                        {
                            return Json(ApiResponse.NotAcceptable(id));
                        }

                    }
                }
                catch (Exception ex)
                {
                    return Json(ApiResponse.InternalServerError(ex.Message));
                }
            }
            else
            {
                return Json(ApiResponse.BadRequest(id));
            }
        }


        public async Task<ActionResult> IntroRazor()
        {
            using(var facade = new BankFacade())
            {
                var list = (await facade.GetAll()).ToList();
                ViewBag.ListData = list.ToList();
                //ViewData["ListData"] = list;
                //Session["ListData"] = list;
                //var model = new AccountModel();
                //model.Account = new Accounts();
                //model.ListBank = new List<Banks>();
                //model.ListTopup = new List<TopUps>();
                //model.Balance = new Balances();
                return View(list);
            }
        }

        public ActionResult Detail(int id)
        {
            using (var facade = new BankFacade())
            {
                var bank = facade.GetByID(id);  
                return View(bank);
            }
        }

        public ActionResult DetailAjax(int id)
        {
            using (var facade = new BankFacade())
            {
                var bank = facade.GetByID(id);
                return PartialView(bank);
            }
        }
    }
}

Fintech.WebMVC/Views/Bank/Detail.cshtml
@model Fintech.Entity.Banks

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Intro  Banks Razor
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Banks</li>
    </ol>
</section>
<section class="content">
    <!-- Default box -->
    <div class="box box-success">
        @using (Html.BeginForm("Update", "Bank", FormMethod.Post))
        {
            <div class="box-header with-border">
                <h3 class="box-title">Bank Detail </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <form name="form1" #form1>
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-4 control-label">
                                Bank ID
                            </div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(md => md.BankID, new { @class="form-control", disabled=true })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 control-label">Bank Name</div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(md => md.BankName, new { @class = "form-control", disabled = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 control-label">Head Office</div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(md => md.HeadOffice, new { @class = "form-control", disabled = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 control-label">Contact Name</div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(md => md.ContactName, new { @class = "form-control", disabled = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 control-label">Contact Phone</div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(md => md.ContactPhone, new { @class = "form-control", disabled = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 control-label">Contact Email</div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(md => md.ContactEmail, new { @class = "form-control", disabled = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 control-label">Account ID</div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(md => md.AccountID, new { @class = "form-control", disabled = true })
                            </div>
                        </div>

                    </div>
                </form>
            </div>
            <div class="box-footer text-center">
                @Html.ActionLink("Back", "IntroRazor", "Bank", new { @class="btn btn-default"})
            </div>
        }
    </div>
</section>

Fintech.WebMVC/Views/Bank/DetailAjax.cshtml
@model Fintech.Entity.Banks

<div class="box box-success">
    @using (Ajax.BeginForm("Update", "Bank", new AjaxOptions { HttpMethod="POST", OnSuccess="UpdateSuccess"}))
    {
        <div class="box-header with-border">
            <h3 class="box-title">Bank Detail </h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-4 control-label">
                            Bank ID
                        </div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(md => md.BankID, new { @class = "form-control", @readonly = true })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 control-label">Bank Name</div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(md => md.BankName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 control-label">Head Office</div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(md => md.HeadOffice, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 control-label">Contact Name</div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(md => md.ContactName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 control-label">Contact Phone</div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(md => md.ContactPhone, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 control-label">Contact Email</div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(md => md.ContactEmail, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 control-label">Account ID</div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(md => md.AccountID, new { @class = "form-control" })
                        </div>
                    </div>

                </div>
           
        </div>
        <div class="box-footer text-center">
            <button type="button" onclick = "backToList()" class="btn btn-default"><i class="fa fa-chevron-left"></i> Back</button>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
        </div>
    }
</div>

Fintech.WebMVC/Views/Bank/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Html.AntiForgeryToken()
<section class="content-header">
    <h1>
        Fintech Banks
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Banks</li>
    </ol>
</section>
<section class="content" ng-controller="ctrl" content>
    <!-- Default box -->
    <div class="box box-success">
        <div id="data-list">
            <div class="box-header with-border">
                <h3 class="box-title">Bank List</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <div id="grid-bank"></div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-right">
                <button id="btn-add" ng-click="addNew()" type="button" class="btn btn-primary"><i class="fa fa-plus"></i> Add New</button>
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

        <div id="data-detail" style="display: none">
            <form name="form1">
                <div class="box-header with-border">
                    <h3 class="box-title">Bank Detail</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-2 control-label">Bank ID</div>
                            <div class="col-md-3">
                                <input ng-model="bank.BankID" type="text" name="BankID" class="form-control" disabled>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 control-label">Bank Name</div>
                            <div class="col-md-3">
                                <input ng-model="bank.BankName" type="text" name="BankName" class="form-control" required maxlength="50">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 control-label">Head Office</div>
                            <div class="col-md-3">
                                <input ng-model="bank.HeadOffice" type="text" name="HeadOffice" class="form-control" required maxlength="50">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 control-label">Contact Name</div>
                            <div class="col-md-3">
                                <input ng-model="bank.ContactName" type="text" name="ContactName" class="form-control" required maxlength="50">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 control-label">Contact Phone</div>
                            <div class="col-md-3">
                                <input ng-model="bank.ContactPhone" type="text" name="ContactPhone" class="form-control" maxlength="30">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 control-label">Contact Email</div>
                            <div class="col-md-3">
                                <input ng-model="bank.ContactEmail" type="text" name="ContactEmail" class="form-control" maxlength="30">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 control-label">Account ID</div>
                            <div class="col-md-3">
                                <input ng-model="bank.AccountID" type="text" name="AccountID" class="form-control" maxlength="30">
                            </div>
                        </div>

                    </div>
                </div>
                <div class="box-footer text-center">
                    <button id="btn-back" ng-click="showList()" type="button" class="btn btn-default"><i class="fa fa-chevron-left"></i> Back</button>
                    <button id="btn-save" ng-click="save()" type="button" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</section>

@section scripts
{
    <script>
        (function () {
            function Bank() {
                return {
                    BankID: 0,
                    BankName: '',
                    HeadOffice: '',
                    ContactName: '',
                    ContactPhone: '',
                    ContactEmail: '',
                    AccountID: 0
                }
            }
            function controller($scope, $http) {
                var scope = $scope;
                var http = $http;

                var grid = gridview('grid-bank', {
                    url: "/Bank/Paging",
                    columns: [
                        {
                            text: "", render: function (c) {
                                var tmpl = "<a action='view'><i class='fa fa-search'></i></a>";
                                tmpl += "<a action='edit'><i class='fa fa-edit'></i></a>";
                                tmpl += "<a action='remove'><i class='fa fa-trash'></i></a>";
                                return tmpl;
                            }
                        },
                        { field: 'BankID', text: 'Bank ID', sortable: true },
                        { field: 'BankName', text: 'Bank Name', sortable: true },
                        { field: 'HeadOffice', text: 'Head Office', sortable: true },
                        { field: 'ContactName', text: 'Contact Name', sortable: true },
                        { field: 'ContactPhone', text: 'Contact Phone', sortable: true },
                        { field: 'ContactEmail', text: 'Contact Email', sortable: true }
                    ],
                    fieldKey: "BankID",
                    view: view,
                    edit: edit,
                    remove: remove
                });

                function view(obj) {
                    state = 'view';
                    scope.bank = obj;
                    scope.$apply();
                    $("[ng-model]").attr("disabled", true);
                    $(".input-group-addon").css('background', '#eee');
                    $("#btn-save").hide();
                    scope.showDetail()
                }
                function edit(obj) {
                    state = 'Update';
                    scope.bank = obj;
                    scope.$apply();
                    $("[ng-model]").not("[name='BankID']")
                        .attr("disabled", false);
                    $("#btn-save").show();
                    scope.showDetail()
                }
                function remove(obj) {
                    Swal.fire({
                        title: 'Confirmation',
                        text: 'Are you sure?',
                        type: 'warning',
                        confirmButtonText: 'YES',
                        confirmButtonColor: 'red',
                        showCancelButton: true,
                        cancelButtonText: 'NO'
                    }).then(function (res) {
                        if (res.value) {
                            http({
                                url: '/Bank/Delete',
                                method: 'POST',
                                data: { id: obj.BankID }
                            }).then(success1)
                                .then(function (res) {
                                    if (res.meta.success) {
                                        Swal.fire("Success", "Delete data success", "success").then(function () { grid.reload() });
                                    } else {
                                        Swal.fire("Error", res.meta.message, "error");
                                    }
                                })
                        }
                    });
                }
                function success1(res) { return res.data; }

                scope.addNew = function () {
                    state = 'Insert';
                    scope.bank = new Bank();
                    $("[ng-model]").not("[name='BankID']")
                        .attr("disabled", false);
                    $("#btn-save").show();
                    scope.showDetail()
                }
                var state = '';
                scope.bank = new Bank();
                scope.showList = function () { $("#data-detail").fadeOut(300, function () { $("#data-list").fadeIn(500); }); }
                scope.showDetail = function () {
                    $("#data-list").fadeOut(300, function () { $("#data-detail").fadeIn(500); });
                    $("[ng-model]").siblings("span").remove();
                }
                scope.save = function () {
                    if (form1.checkValidity()) {
                        http({
                            url: '/Bank/' + state,
                            method: 'POST',
                            data: { 'bank': scope.bank }
                        }).then(success1)
                            .then(function (res) {
                                if (res.meta.success) {
                                    Swal.fire("Success", "Save data success", "success").then(function () { scope.showList(); grid.reload() });
                                } else {
                                    Swal.fire("Error", res.meta.message, "error");
                                }
                            });
                    }
                }

            }

            angular.module("fintech-app").controller("ctrl", controller);
            $("[ng-model]").change(function (e) {
                var span = e.target.parentElement.querySelector("span");
                if (span) $(span).remove();
                if (!e.target.checkValidity()) {
                    span = document.createElement("span");
                    span.style.color = 'red';
                    span.textContent = e.target.validationMessage;
                    e.target.parentElement.appendChild(span);
                }
                $("#btn-save").attr("disabled", !form1.checkValidity());
            });
            $("[banks]").addClass("active"); 
            setTimeout(function () { $("[content]").css("opacity", 1); }, 100);
        }())
    </script>
}

Fintech.WebMVC/Views/Bank/IntroRazor.cshtml
@using Fintech.Entity    
@model List<Banks>
@{
    ViewBag.Title = "IntroRazor";
    List<Banks> list = ViewBag.ListData as List<Banks>;
}

<section class="content-header">
    <h1>
        Intro  Banks Razor
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Banks</li>
    </ol>
</section>
<section class="content">
    <!-- Default box -->
    <div class="box box-success">
        <div id="data-list">
            <div class="box-header with-border">
                <h3 class="box-title">Bank List </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="box-body"> 
                <div id="grid-bank" style="overflow-x: scroll">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td></td>
                                <td>Bank ID</td>
                                <td>Bank Name</td>
                                <td>Head Office</td>
                                <td>Contact Name</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var b in Model)
                            {
                            <tr>
                                <td>
                                    @Ajax.ActionLink("Detail Ajax", "DetailAjax", "Bank", new { id=b.BankID }, new AjaxOptions { HttpMethod="POST", OnSuccess="AjaxSucces" })
                                    @Html.ActionLink("View", "Detail", "Bank", new { id = b.BankID }, new { })
                                    @Html.ActionLink("Edit", "Edit", "Bank", new { id=b.BankID }, new { @class="text-success" })
                                    @Html.ActionLink("Delete", "Delete", "Bank", new { id = b.BankID }, new { @class = "text-danger" })
                                </td>
                                <td>@b.BankID</td>
                                <td>@b.BankName</td>
                                <td>@b.HeadOffice</td>
                                <td>@b.ContactName</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <button onclick="selectAccount()" type="button" class="btn btn-primary"><i class="fa fa-user"></i> Select Account</button>
            </div>
        </div> 

        <div id="data-detail" class="d-none"></div>

        <div id="lookup-account" class="modal fade">
            <div class="modal-dialog modal-lg">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        Select Account
                        <span class="close" data-dismiss="modal">&times;</span>
                    </div>
                    <div class="box-body">
                        <div id="grid-account"></div>
                    </div>
                    <div class="box-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-remove"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        var grid = gridview('grid-account', {
            url: '/Account/paging',
            columns: [
                { text: '', render: function (obj) { return '<a action="select"><i class="fa fa-check"></i></a>'; } },
                { field: 'AccountType', text: 'AccountType', sortable: true },
                { field: 'AccountID', text: 'Account ID', sortable: true },
                { field: 'FirstName', text: 'First Name', sortable: true },
                { field: 'LastName', text: 'Last Name', sortable: true }
            ],
            fieldKey: 'AccountID',
            select: function (obj) {
                console.log(obj);
                $("#lookup-account").modal('hide');
            }
        });

        function selectAccount() {
            $("#lookup-account").modal({ backdrop: 'static' });
        }

        function AjaxSucces(res) {
            $("#data-list").fadeOut(300, function () { $("#data-detail").html(res).fadeIn(300); });
            
            console.log(res);
        }

        function backToList() {
            $("#data-detail").fadeOut(300, function () { $("#data-list").fadeIn(300); });
        }

        function UpdateSuccess(res) {
            if (res.meta.success) {
                Swal.fire("Success", "Save data success!", "success").then(function (r) { location.reload() });
            } else {
                Swal.fire("Error", res.meta.message, "error")
            }
        }
    </script>
    }